"""Fix

Revision ID: b4ea32202c1b
Revises: 77c38c9c3edb
Create Date: 2024-03-30 20:46:55.762044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ea32202c1b'
down_revision: Union[str, None] = '77c38c9c3edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'name')
    # ### end Alembic commands ###
