"""I HATE VSCODE

Revision ID: b965bed6453f
Revises: 980adc31fac6
Create Date: 2024-04-16 14:12:43.331823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b965bed6453f'
down_revision: Union[str, None] = '980adc31fac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('longitude', sa.String(), nullable=False))
    op.add_column('attractions', sa.Column('latitude', sa.String(), nullable=False))
    op.drop_column('attractions', 'location')
    op.add_column('cities', sa.Column('longitude', sa.String(), nullable=False))
    op.add_column('cities', sa.Column('latitude', sa.String(), nullable=False))
    op.drop_column('cities', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cities', 'latitude')
    op.drop_column('cities', 'longitude')
    op.add_column('attractions', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attractions', 'latitude')
    op.drop_column('attractions', 'longitude')
    # ### end Alembic commands ###
