version: '3.7'
services:
  db:
    image: postgres:15
    container_name: database
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  app:
    image: app_image
    build:
      context: .
    container_name:
      app_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command:
      bash -c "alembic revision --autogenerate && alembic upgrade head && gunicorn app.src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:7777"
    ports:
      - 7777:7777